---
galaxy_info:
  author: Emilien Kenler <emilien@kkvesper.jp>
  description: Install and configure a Consul agent
  company: KK Vesper
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
dependencies: []
